language: java
jdk:
  - oraclejdk8


before_install:
  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
  - npm install -g npm@latest
  - npm cache clean

install:
  - npm install -g bower grunt-cli
  - gem update --system
  - gem install compass

before_script:
  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
  - bower install
  - npm install

script: 
  - grunt

notifications:
  email:
    recipients:
      - emre.avsar92@gmail.com
      - c1honegg@hsr.ch
    on_success: change
    on_failure: always

# 
# script:
# # test frontend
#  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
#  - npm install
#  - bower install
#  - grunt
 # maybe not needed?
 # - bower install
 # - grunt compass
 # - grunt test

# TODO (emre): test backend -> run junit tests here
