language: java
jdk:
  - oraclejdk8

install:
  - npm install -g npm@latest
  - npm cache clean
  - npm install -g grunt-cli
  - gem update --system
  - gem install compass

script: 
  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
  - 'npm install -g bower grunt-cli karma'
  - 'bower install'
  - grunt

# 
# script:
# # test frontend
#  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
#  - npm install
#  - bower install
#  - grunt
 # maybe not needed?
 # - bower install
 # - grunt compass
 # - grunt test

# TODO (emre): test backend -> run junit tests here