language: java
jdk:
- oraclejdk8
env:
  global:
  - PLAY_VERSION: 2.3.8
  - ACTIVATOR_VERSION: 1.3.2
  - ACTIVATOR_ZIP_FILE: typesafe-activator-$ACTIVATOR_VERSION-minimal.zip
  - ACTIVATOR_ZIP_URL: http://downloads.typesafe.com/typesafe-activator/$ACTIVATOR_VERSION/$ACTIVATOR_ZIP_FILE
  - ACTIVATOR_BIN: $TRAVIS_BUILD_DIR/quali-t-app/activator-$ACTIVATOR_VERSION-minimal/activator
  - secure: JlgCQyydA3dr29/GBB1S/uAk/BZRWeLW/rqw3kbpwaZXjWwgShYxsHI4iYPOwo+EWQfL7WESkCjdYqvTCsD74WSuwrZOf5ZIhlEMYSGyoPFhwy18pFi3mq+nKh5ZC5bN4UdcXc1fNqFqmA5Uz9SPRMD5I64aq88VTi2wjwimgN8=
before_install:
- cd $TRAVIS_BUILD_DIR/quali-t-app/public/
- npm install -g npm@latest
- npm cache clean
install:
- npm install -g bower grunt-cli
- gem update --system
- gem install compass
before_script:
- cd $TRAVIS_BUILD_DIR/quali-t-app/public/
- bower install
- npm install
- cd $TRAVIS_BUILD_DIR/quali-t-app/
- wget $ACTIVATOR_ZIP_URL
- unzip -q $ACTIVATOR_ZIP_FILE

# disable testing for heroku testing
script:
- cd $TRAVIS_BUILD_DIR/quali-t-app/public/
# - grunt
# - cd $TRAVIS_BUILD_DIR/quali-t-app/
# - $ACTIVATOR_BIN test
#- sbt stage 
after_success:
#- sbt deployHeroku
- $ACTIVATOR_BIN stage deployHeroku