language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: GLBBRZa29GUB6Ee1jHeaP1DaTT9T98I8CVNRJ7CscEjRS6wBRq3CeeQmiBafAEa/QROvI2Isd7rJA48QCTBIhYhZmHVfjCJsYKoaUn/6ZIG/IMWW0rq0PfLRIqiMcV/9iv5/f/iDW2zm828g7+PbNji19BpKMxhR9V5t0oGatXM=
  - PLAY_VERSION: 2.3.8
  - ACTIVATOR_VERSION: 1.3.2
  - ACTIVATOR_ZIP_FILE: typesafe-activator-$ACTIVATOR_VERSION-minimal.zip
  - ACTIVATOR_ZIP_URL: http://downloads.typesafe.com/typesafe-activator/$ACTIVATOR_VERSION/$ACTIVATOR_ZIP_FILE
  - ACTIVATOR_BIN: $TRAVIS_BUILD_DIR/quali-t-app/activator-$ACTIVATOR_VERSION-minimal/activator
  # - QUALIT_BIN: target/universal/stage/bin/quali-t

before_install:
- cd $TRAVIS_BUILD_DIR/quali-t-app/public/
- npm install -g npm@latest
- wget $ACTIVATOR_ZIP_URL
- unzip -q $ACTIVATOR_ZIP_FILE
script:
# disable testing for heroku testing
# - cd $TRAVIS_BUILD_DIR/quali-t-app/public/
# - grunt
# - cd $TRAVIS_BUILD_DIR/quali-t-app/
# - $ACTIVATOR_BIN test
- sbt stage
after_success: sbt deployHeroku



# deploy:
#   provider: heroku
#   api_key:
#     secure: eGQNj3+otZZ+CKBQEbI12BdIs82I0xxsixhKb1adXreh66Djpb6ACTOZAJQ/6sf8fMQfCZfsZ81PBR0NhERppweEG93qqcPfr0aN65ftXHnX8reINJOh+HIObJtyldHspm3/auedqwQ7QJ1ym/0z5v3xefuS4d3+yhJXH9iM+cQ=
#   app: quali-t
#   on:
#     repo: team-qualit/quali-t
  # run:
  # - cd $TRAVIS_BUILD_DIR/quali-t-app/public/
  # - grunt
  # - cd $TRAVIS_BUILD_DIR/quali-t-app/
  # - $QUALIT_BIN -Dhttp.port=8080 -Dconfig.file=$TRAVIS_BUILD_DIR/quali-t-app/conf/prod.conf 