language: java
jdk:
  - oraclejdk8

#install:
#  - npm install -g npm@latest
#  - npm cache clean
#  - npm install -g bower grunt-cli karma
#  - bower install
#  - gem update --system
#  - gem install compass
#
#script: 
#  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
#  - grunt



# next attempt?
before_install:
  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
  - npm install -g npm@latest
  - npm cache clean
  
before_script:
  - npm install -g bower grunt-cli
  - bower install

script: grunt

notifications:
  email:
    recipients:
      - emre.avsar92@gmail.com
    on_success: change
    on_failure: always

# 
# script:
# # test frontend
#  - cd $TRAVIS_BUILD_DIR/quali-t-frontend/
#  - npm install
#  - bower install
#  - grunt
 # maybe not needed?
 # - bower install
 # - grunt compass
 # - grunt test

# TODO (emre): test backend -> run junit tests here