language: java
jdk:
- oraclejdk8
env:
  global:
  - PLAY_VERSION: 2.3.8
  - ACTIVATOR_VERSION: 1.3.2
  - ACTIVATOR_ZIP_FILE: typesafe-activator-$ACTIVATOR_VERSION-minimal.zip
  - ACTIVATOR_ZIP_URL: http://downloads.typesafe.com/typesafe-activator/$ACTIVATOR_VERSION/$ACTIVATOR_ZIP_FILE
  - ACTIVATOR_BIN: $TRAVIS_BUILD_DIR/quali-t-app/activator-$ACTIVATOR_VERSION-minimal/activator
  - secure: J8I3CVK5aor68TqTcbuOSPztECVjH26HGWgT12FR4bedDkWqCWrVOsdtcxVhT+cK5VGjcd3f8EsB9u7MbvnFdr5hvdoXYlGAXqGn58kaWM8chH1qnaiL1zwE4/Fsog53dNTsP6qUHSVW+/VVXnhSDT3jmWRFVPwzCLDoPRVZRdY=
  - HEROKU_API_KEY: J8I3CVK5aor68TqTcbuOSPztECVjH26HGWgT12FR4bedDkWqCWrVOsdtcxVhT+cK5VGjcd3f8EsB9u7MbvnFdr5hvdoXYlGAXqGn58kaWM8chH1qnaiL1zwE4/Fsog53dNTsP6qUHSVW+/VVXnhSDT3jmWRFVPwzCLDoPRVZRdY=
before_install:
- cd $TRAVIS_BUILD_DIR/quali-t-app/public/
- npm install -g npm@latest
- npm cache clean
install:
- npm install -g bower grunt-cli
- gem update --system
- gem install compass
before_script:
- cd $TRAVIS_BUILD_DIR/quali-t-app/public/
- bower install
- npm install
- cd $TRAVIS_BUILD_DIR/quali-t-app/
- wget $ACTIVATOR_ZIP_URL
- unzip -q $ACTIVATOR_ZIP_FILE
script:
- cd $TRAVIS_BUILD_DIR/quali-t-app/public/
- grunt
- cd $TRAVIS_BUILD_DIR/quali-t-app/
- $ACTIVATOR_BIN test
after_success:
- cd $TRAVIS_BUILD_DIR/quali-t-app/
- $ACTIVATOR_BIN stage deployHeroku